<h1>Erik's D20 Database - simple table edits</h1>

<ul>
<li><a href="/simpletable/alignments/">Alignments</a></li>
<li><a href="/simpletable/domains/">Domains</a></li>
<li><a href="/simpletable/featdescriptors/">Feat Descriptors</a></li>
<li><a href="/gamesystem/">Gamesystems</a></li>
<li><a href="/simpletable/pantheons/">Pantheons</a></li>
<li><a href="/simpletable/sourcetypes/">Source Types</a></li>
<li><a href="/simpletable/spelldescriptors/">Spell Descriptors</a></li>
<li><a href="/simpletable/visions/">Vision</a></li>
<li><a href="/simpletable/worlds/">World</a></li>

</ul>