<h1>Erik's D20 Database</h1>

<ul>
<li><a href="/class/">Classes</a></li>
<li><a href="/deity/">Deities</a></li>
<li><a href="/feat/">Feats</a></li>
<li><a href="/race/">Race</a></li>
<li><a href="/skill/">Skills</a></li>
<li><a href="/source/">Sources</a></li>
<li><a href="/spell/">Spells</a></li>
</ul>

<ul>
<li><a href="/armour/">Armour</a></li>
<li><a href="/weapon/">Weapons</a></li>
</ul>

<ul>
<li><a href="/simpletable/alignments/">Alignments</a></li>
<li><a href="/simpletable/deityranks/">Deity Ranks</a></li>
<li><a href="/simpletable/domains/">Domains</a></li>
<li><a href="/simpletable/featdescriptors/">Feat Descriptors</a></li>
<li><a href="/gamesystem/">Gamesystems</a></li>
<li><a href="/simpletable/pantheons/">Pantheons</a></li>
<li><a href="/simpletable/spelldescriptors/">Spell Descriptors</a></li>
<li><a href="/school/">Spell Schools</a></li>
<li><a href="/simpletable/visions/">Vision</a></li>
<li><a href="/simpletable/damagetype/">Weapon damage types</a></li>
<li><a href="/simpletable/worlds/">World</a></li>

</ul>

<ul>
<li><a href="/index/filter-system/">System Filter</a></li>
</ul>

