<h1><?= $this->item['fea_name'] ?></h1>
<table border="0" cellpadding="0" cellspacing="0" class="baseinfotable">
    <tbody>
        <? foreach((array)$this->item['fea_descriptor'] as $value): ?>
            <tr class="baseinfo">
                <td>Type</td>
                <td><?= $value["fty_name"] ?></td>
            </tr>
        <? endforeach; ?>    
        <tr class="baseinfo">
            <td>Short Description</td>
            <td><?= $this->item['fea_shortdescription'] ?></td>
        </tr>
        <tr class="baseinfo">
            <td>Prerequisites</td>
            <td><?= $this->item['fea_prerequisites'] ?></td>
        </tr>
        <tr class="baseinfo">
            <td>Benefit</td>
            <td><?= $this->item['fea_benefit'] ?></td>
        </tr>        
        <tr class="baseinfo">
            <td>Special</td>
            <td><?= $this->item['fea_special'] ?></td>
        </tr>
        <? foreach($this->item['fea_sources'] as $value): ?>
            <tr class="baseinfo">
                <td>Source</td>
                <td><a href="/source/view/<?= $value['src_id'] ?>"><?= $value['src_name'] ?> p <?= $value['fts_page'] ?></id></td>
            </tr>        
        <? endforeach; ?>
        
    </tbody>
</table>


<? foreach($this->item['fea_sources'] as $value): ?>
<img class="hidden cover" src="/img/cover/<?= $value['src_abbriviation'] ?>.jpg">
<? endforeach; ?>

<?php $this->placeholder('buttons')->captureStart(); ?>
<a class="mainmenu" href="/feat/">Feats</a>
<a class="menuedit" href="/feat/edit/<?= $this->item['fea_id'] ?>">Edit</a>
<?php $this->placeholder('buttons')->captureEnd() ?>