<h1><?= $this->item['dei_name'] ?></h1>
<table border="0" cellpadding="0" cellspacing="0" class="baseinfotable">
    <tbody>  
        <? if ($this->item['dei_titles']): ?>
            <tr class="baseinfo">
                <td>Titles</td>
                <td><?= $this->item['dei_titles'] ?></td>
            </tr>   
        <? endif; ?>
        <tr class="baseinfo">
            <td>Rank</td>
            <td><?= $this->item['dra_name'] ?></td>
        </tr>          
        <tr class="baseinfo">
            <td>Pantheon</td>
            <td><?= $this->item['panth_name'] ?></td>
        </tr>    
        <tr class="baseinfo">
            <td>Symbol</td>
            <td><?= $this->item['dei_symbol'] ?></td>
        </tr>           
        <tr class="baseinfo">
            <td>Home Plane</td>
            <td><?= $this->item['dei_homeplane'] ?></td>
        </tr>         
        <tr class="baseinfo">
            <td>Alignment</td>
            <td><?= $this->item['al_name'] ?></td>
        </tr>  
        <tr class="baseinfo">
            <td>Portfolio</td>
            <td><?= $this->item['dei_portfolio'] ?></td>
        </tr>            
        <tr class="baseinfo">
            <td>Worshippers</td>
            <td><?= $this->item['dei_worshippers'] ?></td>
        </tr>          
        <tr class="baseinfo">
            <td>Domains</td>
            <td><?= $this->item['dei_domains'] ?></td>
        </tr>        
        <tr class="baseinfo">
            <td>Favourite weapon</td>
            <td><?= $this->item['dei_weapon'] ?></td>
        </tr>        
  
        <? foreach($this->item['dei_sources'] as $value): ?>
            <tr class="baseinfo">
                <td>Source</td>
                <td><a href="/source/view/<?= $value['src_id'] ?>"><?= $value['src_name'] ?> <?= ($value['deso_page'] ? 'p' . $value['deso_page'] : '') ?></id></td>
            </tr>        
        <? endforeach; ?>

        <tr class="baseinfo">
            <td>Description</td>
            <td><?= $this->item['dei_description'] ?></td>
        </tr>              
            
    </tbody>
</table>


<?php if ($this->item['dei_img']): ?>
<img class="hidden cover" src="/img/deity/<?= $this->item['dei_img'] ?>">
<?php endif; ?>

<? foreach($this->item['dei_sources'] as $value): ?>
<img class="hidden cover" src="/img/cover/<?= $value['src_abbriviation'] ?>.jpg">
<? endforeach; ?>

<?php $this->placeholder('buttons')->captureStart(); ?>
<a class="mainmenu" href="/deity/">Deities</a>
<a class="menuedit" href="/deity/edit/<?= $this->item['dei_id'] ?>">Edit</a>
<?php $this->placeholder('buttons')->captureEnd() ?>